### ISSUE TITLE
any (easy) way to get this to ignore import errors as it does not run in right env?

### ISSUE THREAD

**Issue by maxandersen** [pre-commit/mirrors-pylint#11]
i.e. for mypy you can do the following:
```
-   repo: git://github.com/luismayta/pre-commit-mypy
    sha: '0.1.1'  # Use the sha you want to point at
    hooks:
    -   id: mypy
        args:
        - --ignore-missing-imports
```

**Comment by asottile** [comment]
I'd suggest asking pylint upstream 🤷‍♂️ -- pylint isn't really designed to run in isolation because it does _dynamic_ analysis.  You can read more on this subject [here](https://github.com/pre-commit/pre-commit-hooks/issues/157)

**Comment by maxandersen** [comment]
go it. 

for those maybe seeing this I solved it by using local repo which means it runs with local env setup:

```
-   repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: python3 -m pylint.__main__
        language: system
        types: [python]
```

then imports does get resolved.
