### ISSUE TITLE
Python 3 Support?

### ISSUE THREAD

**Issue by lukelafountaine** [pre-commit/mirrors-pylint#7]
How do you specify which Python version pylint should use? I am using this on a Python 3.5 project and getting warnings like:
`
Unnecessary parens after 'print' keyword (superfluous-parens)
`
So, I am assuming pylint is linting for Python 2.x. How can I specify Python 3?

**Comment by asottile** [comment]
I believe you're looking for [`language_version`](http://pre-commit.com/#overriding-language-version).

For instance:

```yaml
    # ...
    hooks:
    -   id: pylint
        language_version: python3.5
```
